dataset: mot
train_split: mot17_train_cross_val_frame_0_0_to_0_5_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

# train from COCO pre-trained (for ablations)
resume: models/pretrained/r50_deformable_detr-checkpoint.pth
lr: 0.0001
lr_backbone: 0.00001

epochs: 30
lr_drop: 20
